"""Comprehensive drug-drug interaction database.

Each entry: (group_a_names, group_b_names, severity, description, mechanism, recommendation)

Severities: "contraindicated", "high", "moderate", "low"

Sources modeled after: FDA drug interaction tables, BNF, Lexicomp, Micromedex.
This is a rule-based lookup — not a substitute for a pharmacist's clinical judgment.

Coverage: 200+ clinically significant interaction pairs across 18 therapeutic categories.
"""


# ── Type alias for clarity ──────────────────────────────────────────
# (drug_group_a, drug_group_b, severity, description, mechanism, recommendation)
InteractionEntry = tuple[list[str], list[str], str, str, str, str]

INTERACTION_DB: list[InteractionEntry] = [
    # ═══════════════════════════════════════════════════════════════
    # 1. ANTICOAGULANTS & ANTIPLATELETS
    # ═══════════════════════════════════════════════════════════════
    (
        ["warfarin", "coumadin"],
        ["aspirin", "acetylsalicylic acid"],
        "high",
        "Increased bleeding risk — both impair hemostasis via different mechanisms",
        "Warfarin inhibits vitamin K-dependent clotting factors; aspirin inhibits platelet aggregation",
        "Monitor INR closely. Consider alternative antiplatelet if possible. Educate patient on bleeding signs.",
    ),
    (
        ["warfarin", "coumadin"],
        ["ibuprofen", "naproxen", "diclofenac", "nsaid", "ketorolac", "piroxicam", "indomethacin", "meloxicam", "celecoxib"],
        "high",
        "NSAIDs increase bleeding risk and may elevate INR",
        "NSAIDs inhibit platelet function and may displace warfarin from protein binding",
        "Avoid combination when possible. Use acetaminophen for analgesia. If unavoidable, monitor INR every 3–5 days.",
    ),
    (
        ["warfarin", "coumadin"],
        ["fluconazole", "ketoconazole", "itraconazole", "voriconazole", "miconazole"],
        "high",
        "Azole antifungals significantly increase warfarin levels",
        "CYP2C9 and CYP3A4 inhibition increases warfarin concentration",
        "Reduce warfarin dose by 25–50%. Monitor INR within 3–5 days of starting antifungal.",
    ),
    (
        ["warfarin", "coumadin"],
        ["amiodarone", "cordarone"],
        "high",
        "Amiodarone potentiates warfarin — effects may persist weeks after discontinuation",
        "CYP2C9 inhibition by amiodarone; very long half-life (40–55 days)",
        "Reduce warfarin dose by 30–50% when initiating amiodarone. Monitor INR weekly for 6–8 weeks.",
    ),
    (
        ["warfarin", "coumadin"],
        ["metronidazole", "flagyl"],
        "high",
        "Metronidazole increases warfarin anticoagulant effect",
        "Inhibition of CYP2C9 metabolism of S-warfarin",
        "Monitor INR within 3 days. Consider dose reduction. Short courses (<7 days) lower risk.",
    ),
    (
        ["warfarin", "coumadin"],
        ["ciprofloxacin", "levofloxacin", "moxifloxacin", "fluoroquinolone"],
        "moderate",
        "Fluoroquinolones may increase INR in warfarin patients",
        "CYP1A2 inhibition and possible disruption of vitamin K-producing gut flora",
        "Monitor INR within 3–5 days of starting fluoroquinolone.",
    ),
    (
        ["warfarin", "coumadin"],
        ["rifampin", "rifampicin"],
        "high",
        "Rifampin dramatically reduces warfarin effectiveness",
        "Potent CYP inducer (CYP2C9, CYP3A4) — accelerates warfarin metabolism",
        "Avoid combination. If unavoidable, warfarin dose may need 2–5x increase. Monitor INR daily during initiation.",
    ),
    (
        ["warfarin", "coumadin"],
        ["cranberry", "cranberry juice"],
        "moderate",
        "Cranberry products may increase warfarin effect and INR",
        "Possible CYP2C9 inhibition by cranberry flavonoids",
        "Advise patients to limit cranberry intake. Monitor INR if consuming regularly.",
    ),
    (
        ["warfarin", "coumadin"],
        ["vitamin k", "phytonadione"],
        "high",
        "Vitamin K directly antagonizes warfarin's anticoagulant effect",
        "Vitamin K restores clotting factor synthesis that warfarin inhibits",
        "Maintain consistent vitamin K intake. Avoid sudden dietary changes. Leafy greens are high in vitamin K.",
    ),
    (
        ["warfarin", "coumadin"],
        ["phenytoin", "dilantin"],
        "high",
        "Complex bidirectional interaction — initially increases then decreases warfarin effect",
        "Phenytoin induces CYP enzymes but also displaces warfarin from albumin acutely",
        "Monitor INR frequently during initiation and dose changes. Adjust both medications as needed.",
    ),
    (
        ["warfarin", "coumadin"],
        ["sulfamethoxazole", "trimethoprim", "cotrimoxazole", "bactrim"],
        "high",
        "TMP-SMX significantly increases warfarin effect — bleeding risk",
        "CYP2C9 inhibition by sulfamethoxazole; trimethoprim reduces folate metabolism",
        "Monitor INR within 3 days of starting. Reduce warfarin dose by 10–25%. Use alternative antibiotic if possible.",
    ),
    (
        ["heparin", "enoxaparin", "lovenox", "dalteparin"],
        ["aspirin", "clopidogrel", "prasugrel", "ticagrelor", "nsaid"],
        "high",
        "Combined anticoagulant + antiplatelet significantly increases bleeding risk",
        "Additive impairment of hemostasis",
        "Use only when clearly indicated (e.g., ACS). Monitor for bleeding. Ensure PPI co-prescription.",
    ),
    (
        ["clopidogrel", "plavix"],
        ["omeprazole", "esomeprazole"],
        "moderate",
        "Omeprazole/esomeprazole reduce clopidogrel antiplatelet effect",
        "CYP2C19 inhibition reduces conversion of clopidogrel prodrug to active metabolite",
        "Switch to pantoprazole or rabeprazole (minimal CYP2C19 effect). Avoid omeprazole/esomeprazole.",
    ),
    (
        ["dabigatran", "rivaroxaban", "apixaban", "edoxaban", "doac"],
        ["ketoconazole", "itraconazole", "ritonavir", "dronedarone"],
        "contraindicated",
        "Strong P-gp/CYP3A4 inhibitors dramatically increase DOAC levels — bleeding risk",
        "Inhibition of P-glycoprotein efflux and/or CYP3A4 metabolism",
        "Contraindicated combination. Choose alternative antifungal or anticoagulant.",
    ),
    (
        ["dabigatran", "rivaroxaban", "apixaban", "edoxaban", "doac"],
        ["rifampin", "rifampicin", "carbamazepine", "phenytoin", "st john's wort"],
        "high",
        "Strong P-gp/CYP3A4 inducers dramatically reduce DOAC levels — thrombosis risk",
        "Increased P-glycoprotein efflux and CYP3A4 metabolism of DOACs",
        "Avoid combination. If unavoidable, monitor for signs of thrombosis. Consider warfarin with INR monitoring.",
    ),
    (
        ["dabigatran"],
        ["verapamil"],
        "high",
        "Verapamil increases dabigatran levels by 12–180% depending on timing",
        "P-glycoprotein inhibition by verapamil",
        "Reduce dabigatran dose. Administer simultaneously (not 2 hours apart). Monitor for bleeding.",
    ),
    (
        ["aspirin"],
        ["clopidogrel", "prasugrel", "ticagrelor"],
        "moderate",
        "Dual antiplatelet therapy increases bleeding risk but is standard in ACS",
        "Additive platelet inhibition via different pathways (COX-1 + P2Y12)",
        "Standard after coronary stenting (DAPT). PPI co-prescription recommended. Monitor for bleeding.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 2. CARDIOVASCULAR
    # ═══════════════════════════════════════════════════════════════
    (
        ["digoxin", "lanoxin"],
        ["amiodarone", "cordarone"],
        "high",
        "Amiodarone increases digoxin levels by ~70% — toxicity risk",
        "P-glycoprotein inhibition and reduced renal/non-renal clearance of digoxin",
        "Reduce digoxin dose by 50% when starting amiodarone. Monitor digoxin levels and for toxicity signs.",
    ),
    (
        ["digoxin", "lanoxin"],
        ["verapamil", "diltiazem"],
        "high",
        "Calcium channel blockers increase digoxin levels and additive AV block risk",
        "P-glycoprotein inhibition; additive suppression of AV conduction",
        "Monitor digoxin levels. Reduce digoxin dose by 25–50%. Watch for bradycardia.",
    ),
    (
        ["digoxin", "lanoxin"],
        ["furosemide", "hydrochlorothiazide", "thiazide", "loop diuretic"],
        "moderate",
        "Diuretic-induced hypokalemia increases digoxin toxicity risk",
        "Low potassium sensitizes myocardium to digoxin's arrhythmogenic effects",
        "Monitor potassium closely. Maintain K+ > 4.0 mEq/L. Consider potassium-sparing diuretic.",
    ),
    (
        ["digoxin", "lanoxin"],
        ["erythromycin", "clarithromycin", "tetracycline"],
        "high",
        "Macrolides increase digoxin bioavailability — toxicity risk",
        "Macrolides kill gut flora (Eubacterium lentum) that normally inactivate digoxin + P-gp inhibition",
        "Monitor digoxin levels. Reduce dose if needed. Azithromycin is a safer alternative.",
    ),
    (
        ["digoxin", "lanoxin"],
        ["cyclosporine"],
        "high",
        "Cyclosporine increases digoxin levels — nephrotoxicity compounds risk",
        "P-glycoprotein inhibition and reduced renal clearance",
        "Reduce digoxin dose. Monitor levels and renal function closely.",
    ),
    (
        ["ace inhibitor", "enalapril", "lisinopril", "ramipril", "captopril", "perindopril"],
        ["potassium", "spironolactone", "eplerenone", "amiloride", "triamterene", "potassium chloride"],
        "high",
        "Risk of life-threatening hyperkalemia",
        "ACE inhibitors reduce aldosterone → potassium retention + exogenous potassium/K-sparing diuretic",
        "Monitor serum potassium within 1 week. Avoid if K+ > 5.0 mEq/L. Use lowest effective doses.",
    ),
    (
        ["ace inhibitor", "enalapril", "lisinopril", "ramipril"],
        ["arb", "losartan", "valsartan", "telmisartan", "irbesartan", "candesartan"],
        "high",
        "Dual RAAS blockade — increased risk of hyperkalemia, hypotension, and renal failure",
        "Additive suppression of the renin-angiotensin-aldosterone system",
        "Avoid combination. Not recommended by current guidelines. Monitor renal function and K+ if unavoidable.",
    ),
    (
        ["ace inhibitor", "enalapril", "lisinopril", "ramipril"],
        ["aliskiren"],
        "contraindicated",
        "Triple RAAS blockade — contraindicated especially in diabetics",
        "Direct renin inhibitor with ACE inhibitor causes profound RAAS suppression",
        "Contraindicated in patients with diabetes or renal impairment. Avoid combination.",
    ),
    (
        ["beta blocker", "metoprolol", "atenolol", "propranolol", "carvedilol", "bisoprolol"],
        ["verapamil", "diltiazem"],
        "high",
        "Severe bradycardia, AV block, or heart failure risk",
        "Additive negative chronotropic and inotropic effects on the heart",
        "Avoid IV combination. Oral combination only with careful monitoring. Use dihydropyridine CCB (amlodipine) instead.",
    ),
    (
        ["beta blocker", "metoprolol", "atenolol", "propranolol"],
        ["insulin", "glipizide", "glyburide", "sulfonylurea"],
        "moderate",
        "Beta-blockers mask hypoglycemia symptoms and prolong recovery",
        "Beta-blockade prevents tachycardia and tremor — key hypoglycemia warning signs",
        "Prefer cardioselective beta-blockers (metoprolol, bisoprolol). Educate patient on non-adrenergic hypoglycemia signs.",
    ),
    (
        ["beta blocker", "metoprolol", "atenolol", "propranolol"],
        ["clonidine"],
        "high",
        "Rebound hypertensive crisis if clonidine discontinued while on beta-blocker",
        "Beta-blockers prevent compensatory vasodilation during clonidine withdrawal",
        "Discontinue beta-blocker several days before tapering clonidine. Never stop clonidine abruptly.",
    ),
    (
        ["beta blocker", "metoprolol", "propranolol", "atenolol", "carvedilol"],
        ["flecainide", "propafenone"],
        "high",
        "Additive cardiac depression — bradycardia and heart failure risk",
        "Both are negative inotropes; propafenone also inhibits CYP2D6 increasing metoprolol levels",
        "Monitor ECG and heart rate. Use lowest effective doses. Avoid in patients with structural heart disease.",
    ),
    (
        ["amiodarone", "cordarone"],
        ["simvastatin", "lovastatin"],
        "high",
        "Increased statin levels — rhabdomyolysis risk",
        "Amiodarone inhibits CYP3A4 metabolism of statins",
        "Limit simvastatin to 20 mg/day with amiodarone. Consider pravastatin or rosuvastatin as alternatives.",
    ),
    (
        ["amiodarone", "cordarone"],
        ["fluoroquinolone", "ciprofloxacin", "levofloxacin", "moxifloxacin"],
        "high",
        "QT prolongation — torsades de pointes risk",
        "Both amiodarone and fluoroquinolones independently prolong the QT interval",
        "Avoid combination. Monitor ECG if unavoidable. Use azithromycin cautiously as alternative.",
    ),
    (
        ["amiodarone", "cordarone"],
        ["metoprolol", "atenolol", "beta blocker"],
        "high",
        "Severe bradycardia and AV block risk",
        "Additive negative chronotropic effects; amiodarone also inhibits CYP2D6 increasing beta-blocker levels",
        "Monitor heart rate and ECG closely. Reduce beta-blocker dose. Use lowest effective doses.",
    ),
    (
        ["nitrate", "nitroglycerin", "isosorbide"],
        ["sildenafil", "tadalafil", "vardenafil", "pde5 inhibitor"],
        "contraindicated",
        "Severe life-threatening hypotension",
        "Additive vasodilation via NO/cGMP pathway",
        "Absolutely contraindicated. Sildenafil must be stopped 24h before nitrates; tadalafil 48h.",
    ),
    (
        ["amlodipine", "nifedipine", "felodipine", "dihydropyridine"],
        ["simvastatin"],
        "moderate",
        "Amlodipine increases simvastatin levels — rhabdomyolysis risk",
        "Mild CYP3A4 inhibition by amlodipine increases simvastatin exposure",
        "Limit simvastatin to 20 mg/day with amlodipine. Atorvastatin up to 40mg is acceptable.",
    ),
    (
        ["statin", "atorvastatin", "simvastatin", "rosuvastatin", "pravastatin"],
        ["gemfibrozil"],
        "high",
        "Gemfibrozil dramatically increases statin levels — rhabdomyolysis risk",
        "OATP1B1 and CYP2C8 inhibition by gemfibrozil reduces statin metabolism",
        "Avoid gemfibrozil + statin combination. If fibrate needed, fenofibrate is safer.",
    ),
    (
        ["statin", "simvastatin", "atorvastatin"],
        ["grapefruit", "grapefruit juice"],
        "moderate",
        "Grapefruit increases statin levels — myopathy risk",
        "Furanocoumarins in grapefruit irreversibly inhibit intestinal CYP3A4",
        "Avoid grapefruit with simvastatin/lovastatin. Small amounts OK with atorvastatin. Rosuvastatin/pravastatin unaffected.",
    ),
    (
        ["ivabradine", "corlanor"],
        ["verapamil", "diltiazem"],
        "contraindicated",
        "Severe bradycardia — heart rate may drop dangerously",
        "Additive heart rate reduction; verapamil/diltiazem also inhibit CYP3A4 increasing ivabradine levels",
        "Contraindicated combination. Use beta-blocker or dihydropyridine CCB instead.",
    ),
    (
        ["ranolazine"],
        ["ketoconazole", "itraconazole", "ritonavir", "nelfinavir"],
        "contraindicated",
        "Strong CYP3A4 inhibitors dramatically increase ranolazine levels — QT prolongation",
        "CYP3A4 is primary metabolic pathway for ranolazine",
        "Contraindicated combination. Avoid strong CYP3A4 inhibitors.",
    ),
    (
        ["doxazosin", "prazosin", "terazosin", "alpha blocker"],
        ["sildenafil", "tadalafil", "pde5 inhibitor"],
        "high",
        "First-dose hypotension — severe drop in blood pressure",
        "Additive vasodilation via alpha-blockade and PDE5 inhibition",
        "Start PDE5 inhibitor at lowest dose. Separate administration by 4+ hours. Monitor for orthostatic hypotension.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 3. DIABETES
    # ═══════════════════════════════════════════════════════════════
    (
        ["metformin", "glucophage"],
        ["contrast", "contrast dye", "iodinated contrast"],
        "high",
        "Risk of metformin-associated lactic acidosis in setting of contrast nephropathy",
        "Contrast can impair renal function → metformin accumulation → lactic acidosis",
        "Hold metformin 48h before and after iodinated contrast. Check eGFR before resuming.",
    ),
    (
        ["metformin", "glucophage"],
        ["alcohol", "ethanol"],
        "moderate",
        "Increased risk of lactic acidosis",
        "Alcohol impairs hepatic gluconeogenesis and lactate metabolism",
        "Advise patients to limit alcohol intake. Avoid binge drinking. Monitor for nausea and malaise.",
    ),
    (
        ["metformin", "glucophage"],
        ["topiramate", "zonisamide", "acetazolamide"],
        "moderate",
        "Carbonic anhydrase inhibitors increase metformin-associated lactic acidosis risk",
        "Metabolic acidosis from CA inhibitors compounds metformin's lactate effect",
        "Monitor lactate and bicarbonate levels. Avoid in patients with renal impairment.",
    ),
    (
        ["insulin"],
        ["fluoroquinolone", "ciprofloxacin", "levofloxacin", "moxifloxacin"],
        "moderate",
        "Fluoroquinolones can cause unpredictable blood glucose changes",
        "Altered insulin secretion — both hypo- and hyperglycemia reported",
        "Monitor blood glucose more frequently. Adjust insulin dose as needed.",
    ),
    (
        ["insulin"],
        ["beta blocker", "propranolol", "atenolol", "metoprolol"],
        "moderate",
        "Beta-blockers mask hypoglycemia symptoms and delay recovery",
        "Beta-blockade prevents tachycardia and sweating that warn of low blood sugar",
        "Use cardioselective beta-blockers. Educate on non-adrenergic hypoglycemia signs (hunger, confusion).",
    ),
    (
        ["insulin"],
        ["corticosteroid", "prednisone", "prednisolone", "dexamethasone"],
        "high",
        "Corticosteroids significantly increase blood glucose — may require insulin dose increase",
        "Steroids increase hepatic gluconeogenesis and reduce peripheral glucose uptake",
        "Monitor glucose closely. May need 20–50% insulin dose increase. Adjust down when tapering steroids.",
    ),
    (
        ["sulfonylurea", "glipizide", "glyburide", "glimepiride", "gliclazide"],
        ["fluconazole", "miconazole"],
        "high",
        "Azoles significantly increase sulfonylurea levels — severe hypoglycemia risk",
        "CYP2C9 inhibition reduces sulfonylurea metabolism",
        "Reduce sulfonylurea dose by 50%. Monitor blood glucose closely. Consider alternative antifungal.",
    ),
    (
        ["sulfonylurea", "glipizide", "glyburide", "glimepiride"],
        ["alcohol", "ethanol"],
        "high",
        "Severe prolonged hypoglycemia risk — disulfiram-like reaction with chlorpropamide",
        "Alcohol enhances insulin secretion and impairs hepatic gluconeogenesis",
        "Warn patients about alcohol risk. Monitor glucose closely if patient drinks.",
    ),
    (
        ["sglt2 inhibitor", "empagliflozin", "dapagliflozin", "canagliflozin"],
        ["furosemide", "loop diuretic", "thiazide", "hydrochlorothiazide"],
        "moderate",
        "Increased risk of dehydration, hypotension, and acute kidney injury",
        "Additive diuretic effect — SGLT2 inhibitors cause osmotic diuresis",
        "Monitor volume status and renal function. Reduce diuretic dose if needed. Ensure adequate hydration.",
    ),
    (
        ["pioglitazone", "rosiglitazone", "thiazolidinedione"],
        ["insulin"],
        "high",
        "Increased risk of heart failure and severe hypoglycemia",
        "TZDs cause fluid retention; combined with insulin amplifies weight gain and edema",
        "Monitor for heart failure symptoms (edema, dyspnea, weight gain). Reduce insulin dose. Avoid in NYHA III-IV.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 4. CNS / PSYCHIATRY
    # ═══════════════════════════════════════════════════════════════
    (
        ["ssri", "fluoxetine", "sertraline", "paroxetine", "citalopram", "escitalopram", "fluvoxamine"],
        ["maoi", "phenelzine", "tranylcypromine", "isocarboxazid", "selegiline", "linezolid"],
        "contraindicated",
        "Serotonin syndrome — potentially fatal",
        "Excessive serotonergic activity from dual blockade of serotonin reuptake and metabolism",
        "Contraindicated. Requires 2-week washout between SSRI and MAOI (5 weeks for fluoxetine).",
    ),
    (
        ["ssri", "fluoxetine", "sertraline", "paroxetine", "citalopram", "escitalopram"],
        ["tramadol", "fentanyl", "meperidine", "dextromethorphan"],
        "high",
        "Risk of serotonin syndrome",
        "Tramadol/fentanyl/DXM inhibit serotonin reuptake; combined with SSRI causes excess serotonin",
        "Avoid combination when possible. If used, start low dose and monitor for agitation, hyperthermia, clonus.",
    ),
    (
        ["ssri", "fluoxetine", "sertraline", "paroxetine", "citalopram"],
        ["nsaid", "aspirin", "ibuprofen", "naproxen"],
        "moderate",
        "SSRIs + NSAIDs increase GI bleeding risk 3–6 fold",
        "SSRIs deplete platelet serotonin needed for aggregation; NSAIDs damage gastric mucosa",
        "Co-prescribe PPI (omeprazole/pantoprazole) for GI protection. Monitor for bleeding signs.",
    ),
    (
        ["ssri", "snri", "fluoxetine", "sertraline", "paroxetine", "venlafaxine", "duloxetine"],
        ["triptans", "sumatriptan", "rizatriptan", "zolmitriptan", "eletriptan"],
        "high",
        "Risk of serotonin syndrome — especially with higher doses",
        "Triptans are 5-HT1B/1D agonists; combined with serotonin reuptake inhibitors increases serotonin activity",
        "Use lowest effective triptan dose. Monitor for serotonin syndrome symptoms for 24 hours after triptan use.",
    ),
    (
        ["fluoxetine", "paroxetine"],
        ["tamoxifen"],
        "high",
        "Strong CYP2D6 inhibitors reduce tamoxifen effectiveness — cancer recurrence risk",
        "Fluoxetine/paroxetine block CYP2D6 conversion of tamoxifen to active endoxifen",
        "Switch to SSRI with minimal CYP2D6 effect: citalopram, escitalopram, or venlafaxine.",
    ),
    (
        ["fluoxetine", "paroxetine", "fluvoxamine"],
        ["metoprolol", "propranolol"],
        "moderate",
        "CYP2D6 inhibition by SSRIs increases beta-blocker levels — bradycardia risk",
        "Fluoxetine/paroxetine are potent CYP2D6 inhibitors; metoprolol is CYP2D6 substrate",
        "Monitor heart rate and blood pressure. Consider atenolol (not CYP2D6 metabolized) as alternative.",
    ),
    (
        ["lithium"],
        ["nsaid", "ibuprofen", "naproxen", "diclofenac", "indomethacin", "ketorolac"],
        "high",
        "NSAIDs increase lithium levels — toxicity risk",
        "NSAIDs reduce renal lithium clearance by ~20%",
        "Monitor lithium levels within 5 days. Sulindac may be safest NSAID. Aspirin low-dose has less effect.",
    ),
    (
        ["lithium"],
        ["ace inhibitor", "enalapril", "lisinopril", "ramipril"],
        "high",
        "ACE inhibitors reduce lithium excretion — toxicity risk",
        "Reduced GFR and altered sodium handling impair lithium clearance",
        "Monitor lithium levels closely. Reduce lithium dose if needed. Watch for tremor, confusion, ataxia.",
    ),
    (
        ["lithium"],
        ["furosemide", "hydrochlorothiazide", "thiazide"],
        "high",
        "Thiazide diuretics increase lithium levels by 25–40%",
        "Sodium depletion increases proximal tubular lithium reabsorption",
        "Reduce lithium dose by 25–50%. Monitor lithium levels. Loop diuretics are somewhat safer.",
    ),
    (
        ["lithium"],
        ["carbamazepine"],
        "high",
        "Neurotoxicity risk even with therapeutic levels of both drugs",
        "Additive CNS toxicity; carbamazepine may increase lithium's neurotoxic effects",
        "Monitor closely for neurotoxicity (ataxia, confusion, tremor). Check levels of both drugs.",
    ),
    (
        ["benzodiazepine", "diazepam", "lorazepam", "alprazolam", "clonazepam", "midazolam"],
        ["opioid", "morphine", "oxycodone", "hydrocodone", "fentanyl", "codeine", "tramadol", "methadone"],
        "high",
        "Combined CNS depression — respiratory failure and death risk",
        "Additive CNS/respiratory depression via GABA and opioid receptor pathways",
        "FDA boxed warning. Avoid combination unless no alternative. Use lowest doses for shortest duration.",
    ),
    (
        ["benzodiazepine", "diazepam", "lorazepam", "alprazolam", "clonazepam"],
        ["alcohol", "ethanol"],
        "high",
        "Life-threatening CNS and respiratory depression",
        "Additive GABA-A receptor potentiation causing profound sedation",
        "Absolute avoidance recommended. Educate patients. Risk of fatal respiratory depression.",
    ),
    (
        ["carbamazepine", "tegretol"],
        ["oral contraceptive", "ethinyl estradiol", "birth control"],
        "high",
        "Carbamazepine reduces oral contraceptive effectiveness — unplanned pregnancy risk",
        "CYP3A4 induction accelerates estrogen metabolism",
        "Use non-oral contraception (IUD, depot) or higher-dose estrogen formulation.",
    ),
    (
        ["carbamazepine", "tegretol"],
        ["erythromycin", "clarithromycin"],
        "high",
        "Macrolides increase carbamazepine levels — toxicity risk (ataxia, diplopia, nausea)",
        "CYP3A4 inhibition by macrolides slows carbamazepine metabolism",
        "Use azithromycin as alternative. Monitor carbamazepine levels if macrolide unavoidable.",
    ),
    (
        ["carbamazepine", "tegretol"],
        ["valproate", "valproic acid", "divalproex"],
        "high",
        "Complex interaction — carbamazepine levels decrease, active metabolite increases; valproate decreases",
        "Carbamazepine induces valproate metabolism; valproate inhibits epoxide hydrolase increasing toxic metabolite",
        "Monitor levels of both drugs. Watch for carbamazepine toxicity signs despite 'normal' parent drug levels.",
    ),
    (
        ["valproate", "valproic acid", "divalproex"],
        ["lamotrigine"],
        "high",
        "Valproate doubles lamotrigine levels — Stevens-Johnson syndrome risk",
        "Valproate inhibits glucuronidation of lamotrigine",
        "Reduce lamotrigine dose by 50% when combining. Titrate very slowly (25mg every 2 weeks).",
    ),
    (
        ["valproate", "valproic acid"],
        ["carbapenem", "meropenem", "imipenem", "ertapenem", "doripenem"],
        "contraindicated",
        "Carbapenems reduce valproate levels by 60–90% within 24 hours — seizure breakthrough",
        "Carbapenems inhibit valproate glucuronide hydrolysis, preventing enterohepatic recirculation",
        "Avoid combination. If carbapenem essential, switch to alternative anticonvulsant before starting.",
    ),
    (
        ["quetiapine", "olanzapine", "risperidone", "aripiprazole", "antipsychotic"],
        ["metoclopramide", "prochlorperazine", "promethazine"],
        "moderate",
        "Additive dopamine blockade — increased risk of extrapyramidal symptoms and NMS",
        "Both block D2 dopamine receptors; combined effect amplifies movement disorder risk",
        "Avoid combination. Use ondansetron for nausea instead. Monitor for rigidity, dystonia.",
    ),
    (
        ["clozapine"],
        ["carbamazepine"],
        "contraindicated",
        "Both cause bone marrow suppression — fatal agranulocytosis risk",
        "Additive myelosuppressive effects; carbamazepine also induces CYP1A2 reducing clozapine levels",
        "Absolutely contraindicated. Use valproate or lamotrigine as alternative mood stabilizer.",
    ),
    (
        ["clozapine"],
        ["ciprofloxacin", "fluvoxamine"],
        "high",
        "CYP1A2 inhibitors dramatically increase clozapine levels — seizure and sedation risk",
        "Clozapine is primarily metabolized by CYP1A2; inhibitors cause rapid accumulation",
        "Reduce clozapine dose by 50%. Monitor clozapine levels closely. Use alternative antibiotic if possible.",
    ),
    (
        ["maoi", "phenelzine", "tranylcypromine"],
        ["tyramine", "aged cheese", "red wine", "fermented food"],
        "contraindicated",
        "Hypertensive crisis — risk of stroke and death",
        "MAOIs prevent tyramine breakdown; tyramine causes massive norepinephrine release",
        "Strict dietary restrictions required. Educate patient on tyramine-rich foods. Carry nifedipine for emergencies.",
    ),
    (
        ["trazodone"],
        ["ketoconazole", "itraconazole", "ritonavir"],
        "high",
        "Strong CYP3A4 inhibitors significantly increase trazodone levels — sedation and hypotension",
        "CYP3A4 is the primary metabolic pathway for trazodone",
        "Reduce trazodone dose. Monitor for excessive sedation and orthostatic hypotension.",
    ),
    (
        ["bupropion", "wellbutrin"],
        ["maoi", "phenelzine", "tranylcypromine"],
        "contraindicated",
        "Hypertensive crisis and seizure risk",
        "Bupropion inhibits dopamine/norepinephrine reuptake; MAOIs prevent catecholamine breakdown",
        "Contraindicated. Requires 14-day washout between drugs.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 5. ANTIBIOTICS & ANTI-INFECTIVES
    # ═══════════════════════════════════════════════════════════════
    (
        ["aminoglycoside", "gentamicin", "tobramycin", "amikacin"],
        ["vancomycin"],
        "high",
        "Additive nephrotoxicity and ototoxicity",
        "Both drugs are independently nephrotoxic; combination amplifies renal tubular damage",
        "Monitor renal function (creatinine, BUN) daily. Monitor drug levels. Hydrate patient well.",
    ),
    (
        ["aminoglycoside", "gentamicin", "tobramycin", "amikacin"],
        ["furosemide", "loop diuretic"],
        "high",
        "Loop diuretics enhance aminoglycoside ototoxicity and nephrotoxicity",
        "Furosemide causes cochlear damage synergistic with aminoglycoside effect",
        "Avoid concurrent use when possible. Monitor hearing and renal function. Use alternative diuretic.",
    ),
    (
        ["aminoglycoside", "gentamicin", "tobramycin", "amikacin"],
        ["amphotericin b"],
        "high",
        "Additive nephrotoxicity — acute kidney injury risk",
        "Both are independently nephrotoxic; amphotericin B damages renal tubular cells",
        "Monitor renal function daily. Consider liposomal amphotericin B to reduce nephrotoxicity.",
    ),
    (
        ["aminoglycoside", "gentamicin", "tobramycin"],
        ["neuromuscular blocker", "succinylcholine", "vecuronium", "rocuronium"],
        "high",
        "Aminoglycosides enhance neuromuscular blockade — prolonged paralysis",
        "Aminoglycosides inhibit presynaptic acetylcholine release at the neuromuscular junction",
        "Monitor neuromuscular function closely. May need reduced blocker dose. Calcium may partially reverse.",
    ),
    (
        ["macrolide", "erythromycin", "clarithromycin", "azithromycin"],
        ["statin", "simvastatin", "atorvastatin", "lovastatin"],
        "high",
        "Macrolides increase statin levels — rhabdomyolysis risk",
        "CYP3A4 inhibition by erythromycin/clarithromycin (azithromycin has minimal effect)",
        "Hold statin during macrolide course, or switch to azithromycin. Pravastatin/rosuvastatin are safer.",
    ),
    (
        ["macrolide", "erythromycin", "clarithromycin"],
        ["theophylline", "aminophylline"],
        "high",
        "Macrolides increase theophylline levels — seizure/arrhythmia risk",
        "CYP1A2 and CYP3A4 inhibition reduces theophylline clearance",
        "Monitor theophylline levels. Reduce dose by 25%. Azithromycin is a safer alternative.",
    ),
    (
        ["erythromycin", "clarithromycin"],
        ["cisapride", "pimozide", "terfenadine", "astemizole"],
        "contraindicated",
        "Fatal QT prolongation and torsades de pointes",
        "CYP3A4 inhibition by macrolides causes accumulation of QT-prolonging substrates",
        "Absolutely contraindicated. Use azithromycin or alternative non-macrolide antibiotic.",
    ),
    (
        ["fluoroquinolone", "ciprofloxacin", "levofloxacin", "moxifloxacin"],
        ["antacid", "aluminum", "magnesium", "calcium", "iron", "zinc", "sucralfate"],
        "high",
        "Divalent cations chelate fluoroquinolones — drastically reduced absorption",
        "Metal ions form insoluble complexes in the GI tract preventing quinolone absorption",
        "Administer fluoroquinolone 2h before or 6h after cation-containing products.",
    ),
    (
        ["fluoroquinolone", "ciprofloxacin", "levofloxacin", "moxifloxacin"],
        ["corticosteroid", "prednisolone", "dexamethasone", "prednisone", "methylprednisolone"],
        "moderate",
        "Increased risk of tendon rupture, especially in elderly",
        "Both fluoroquinolones and corticosteroids independently weaken tendon tissue",
        "Avoid combination in patients >60 years. Monitor for tendon pain. Discontinue at first sign of tendinitis.",
    ),
    (
        ["moxifloxacin"],
        ["amiodarone", "sotalol", "class iii antiarrhythmic"],
        "contraindicated",
        "Additive QT prolongation — torsades de pointes risk",
        "Both significantly prolong the QT interval via different mechanisms",
        "Contraindicated. Use alternative antibiotic without QT-prolonging effects.",
    ),
    (
        ["trimethoprim", "cotrimoxazole", "bactrim"],
        ["methotrexate"],
        "high",
        "Trimethoprim increases methotrexate toxicity — pancytopenia risk",
        "Both are folate antagonists; trimethoprim reduces renal clearance of methotrexate",
        "Avoid combination. If unavoidable, monitor CBC closely and supplement with folinic acid.",
    ),
    (
        ["trimethoprim", "cotrimoxazole"],
        ["ace inhibitor", "enalapril", "lisinopril", "arb", "losartan", "spironolactone"],
        "high",
        "Severe hyperkalemia — sudden cardiac death risk",
        "Trimethoprim acts like a potassium-sparing diuretic in the collecting tubule",
        "Monitor potassium within 48 hours. Avoid in elderly with renal impairment. Short courses are safer.",
    ),
    (
        ["rifampin", "rifampicin"],
        ["oral contraceptive", "ethinyl estradiol"],
        "high",
        "Rifampin dramatically reduces contraceptive effectiveness",
        "Potent CYP3A4 induction accelerates estrogen and progestin metabolism",
        "Use non-hormonal contraception during and 4 weeks after rifampin. IUD is preferred.",
    ),
    (
        ["rifampin", "rifampicin"],
        ["protease inhibitor", "ritonavir", "lopinavir", "atazanavir", "darunavir"],
        "contraindicated",
        "Rifampin reduces protease inhibitor levels by 75–95% — treatment failure",
        "Potent CYP3A4 induction; irreversible enzyme induction lasts 2+ weeks",
        "Contraindicated. Use rifabutin as alternative (less enzyme induction).",
    ),
    (
        ["isoniazid", "inh"],
        ["acetaminophen", "paracetamol"],
        "moderate",
        "Isoniazid increases risk of hepatotoxicity from acetaminophen",
        "CYP2E1 induction by isoniazid increases toxic metabolite NAPQI formation",
        "Limit acetaminophen to <2g/day. Monitor liver function. Avoid in patients with liver disease.",
    ),
    (
        ["isoniazid"],
        ["carbamazepine"],
        "high",
        "Isoniazid increases carbamazepine levels — toxicity (ataxia, nystagmus)",
        "CYP3A4 inhibition by isoniazid reduces carbamazepine metabolism",
        "Monitor carbamazepine levels. Reduce dose as needed. Watch for toxicity signs.",
    ),
    (
        ["dapsone"],
        ["trimethoprim"],
        "moderate",
        "Both inhibit folate pathway — increased risk of methemoglobinemia",
        "Additive oxidative stress on hemoglobin from both drugs",
        "Monitor for cyanosis and methemoglobin levels. Check G6PD status before starting.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 6. IMMUNOSUPPRESSANTS & ONCOLOGY
    # ═══════════════════════════════════════════════════════════════
    (
        ["cyclosporine", "tacrolimus"],
        ["nsaid", "ibuprofen", "naproxen", "diclofenac"],
        "high",
        "Additive nephrotoxicity — acute kidney injury risk",
        "Both calcineurin inhibitors and NSAIDs impair renal blood flow",
        "Avoid NSAIDs in transplant patients. Use acetaminophen for pain. Monitor renal function.",
    ),
    (
        ["cyclosporine", "tacrolimus"],
        ["ketoconazole", "itraconazole", "fluconazole", "voriconazole"],
        "high",
        "Azole antifungals significantly increase calcineurin inhibitor levels",
        "CYP3A4 and P-glycoprotein inhibition reduces CNI metabolism",
        "Reduce cyclosporine/tacrolimus dose by 50–75%. Monitor trough levels closely.",
    ),
    (
        ["cyclosporine", "tacrolimus"],
        ["aminoglycoside", "gentamicin", "tobramycin", "amikacin"],
        "high",
        "Additive nephrotoxicity — acute kidney injury risk",
        "Both independently nephrotoxic via different mechanisms",
        "Avoid combination. Monitor renal function and CNI trough levels daily.",
    ),
    (
        ["cyclosporine"],
        ["simvastatin", "atorvastatin", "lovastatin"],
        "contraindicated",
        "Cyclosporine dramatically increases statin levels — rhabdomyolysis risk",
        "CYP3A4 and OATP1B1 inhibition by cyclosporine; reduced statin clearance",
        "Use pravastatin or fluvastatin (minimal interaction). Simvastatin/lovastatin contraindicated.",
    ),
    (
        ["tacrolimus"],
        ["potassium", "potassium chloride", "spironolactone"],
        "high",
        "Hyperkalemia risk — tacrolimus causes potassium retention",
        "Tacrolimus suppresses aldosterone and reduces renal potassium excretion",
        "Monitor potassium closely. Avoid potassium supplements unless documented hypokalemia.",
    ),
    (
        ["methotrexate"],
        ["nsaid", "ibuprofen", "naproxen", "aspirin"],
        "high",
        "NSAIDs reduce methotrexate clearance — severe pancytopenia risk",
        "NSAIDs reduce renal blood flow and compete for tubular secretion of methotrexate",
        "Avoid NSAIDs with high-dose MTX. Low-dose MTX + short NSAID courses may be acceptable with monitoring.",
    ),
    (
        ["methotrexate"],
        ["probenecid"],
        "high",
        "Probenecid significantly increases methotrexate levels — severe toxicity",
        "Probenecid inhibits renal tubular secretion of methotrexate",
        "Avoid combination with high-dose methotrexate. Monitor MTX levels and CBC closely.",
    ),
    (
        ["methotrexate"],
        ["penicillin", "amoxicillin", "piperacillin"],
        "moderate",
        "Penicillins may reduce methotrexate clearance — toxicity risk",
        "Competition for renal tubular secretion",
        "Monitor methotrexate levels and renal function. Watch for mucositis and cytopenias.",
    ),
    (
        ["azathioprine", "mercaptopurine", "6-mp"],
        ["allopurinol"],
        "contraindicated",
        "Allopurinol increases azathioprine/6-MP levels 3–5x — fatal pancytopenia",
        "Allopurinol inhibits xanthine oxidase, blocking 6-MP inactivation pathway",
        "Reduce azathioprine/6-MP dose by 75% if allopurinol essential. Or use febuxostat (less interaction).",
    ),
    (
        ["mycophenolate", "cellcept"],
        ["cholestyramine", "colestipol"],
        "high",
        "Bile acid sequestrants reduce mycophenolate absorption by 40%",
        "Interruption of enterohepatic recirculation of mycophenolic acid",
        "Avoid combination. If bile acid sequestrant needed, separate by 2+ hours.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 7. GASTROENTEROLOGY
    # ═══════════════════════════════════════════════════════════════
    (
        ["ppi", "omeprazole", "pantoprazole", "lansoprazole", "rabeprazole", "esomeprazole"],
        ["clopidogrel", "plavix"],
        "moderate",
        "PPIs (especially omeprazole) may reduce clopidogrel effectiveness",
        "CYP2C19 inhibition reduces clopidogrel bioactivation",
        "Prefer pantoprazole (least CYP2C19 inhibition). Avoid omeprazole/esomeprazole with clopidogrel.",
    ),
    (
        ["ppi", "omeprazole", "pantoprazole", "lansoprazole"],
        ["iron", "ferrous sulfate", "ferrous fumarate"],
        "low",
        "PPIs reduce iron absorption — may worsen iron-deficiency anemia",
        "Acid suppression impairs conversion of ferric to ferrous iron needed for absorption",
        "Monitor iron levels. Consider IV iron if oral supplementation fails. Take iron on empty stomach.",
    ),
    (
        ["ppi", "omeprazole", "pantoprazole"],
        ["levothyroxine", "thyroid"],
        "low",
        "PPIs may reduce levothyroxine absorption",
        "Gastric acid is needed for dissolution of levothyroxine tablets",
        "Take levothyroxine 30–60 min before PPI. Monitor TSH levels. Consider liquid formulation.",
    ),
    (
        ["ppi", "omeprazole", "pantoprazole", "lansoprazole"],
        ["methotrexate"],
        "moderate",
        "PPIs may increase methotrexate levels — toxicity with high-dose MTX",
        "PPIs inhibit H+/K+ ATPase which also mediates renal MTX secretion",
        "Hold PPI during high-dose methotrexate cycles. Monitor MTX levels.",
    ),
    (
        ["ppi", "omeprazole", "pantoprazole"],
        ["bisphosphonate", "alendronate", "risedronate"],
        "low",
        "PPIs may reduce bisphosphonate absorption and independently increase fracture risk",
        "Altered gastric pH affects bisphosphonate dissolution; chronic PPI use weakens bone",
        "Monitor bone density. Ensure adequate calcium/vitamin D. Re-evaluate PPI necessity.",
    ),
    (
        ["metoclopramide", "domperidone"],
        ["levodopa", "carbidopa"],
        "moderate",
        "D2 antagonists reduce levodopa effectiveness in Parkinson's disease",
        "Metoclopramide blocks dopamine receptors that levodopa activates",
        "Avoid metoclopramide in Parkinson's. Domperidone (doesn't cross BBB) is safer alternative.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 8. RESPIRATORY
    # ═══════════════════════════════════════════════════════════════
    (
        ["theophylline", "aminophylline"],
        ["ciprofloxacin"],
        "high",
        "Ciprofloxacin increases theophylline levels by 15–30% — seizure risk",
        "CYP1A2 inhibition reduces theophylline clearance",
        "Monitor theophylline levels. Reduce dose by 30%. Use levofloxacin/moxifloxacin as alternatives.",
    ),
    (
        ["theophylline", "aminophylline"],
        ["fluvoxamine"],
        "contraindicated",
        "Fluvoxamine increases theophylline levels by 2–3x — severe toxicity",
        "Potent CYP1A2 inhibition by fluvoxamine dramatically slows theophylline metabolism",
        "Contraindicated. If SSRI needed, use sertraline or citalopram (minimal CYP1A2 effect).",
    ),
    (
        ["theophylline", "aminophylline"],
        ["rifampin", "rifampicin"],
        "high",
        "Rifampin reduces theophylline levels by 25–50%",
        "CYP1A2 induction by rifampin accelerates theophylline clearance",
        "Increase theophylline dose. Monitor levels closely. Adjust when rifampin discontinued.",
    ),
    (
        ["beta blocker", "propranolol", "atenolol", "metoprolol"],
        ["salbutamol", "albuterol", "salmeterol", "formoterol", "beta-agonist"],
        "moderate",
        "Beta-blockers antagonize bronchodilator effect — may worsen asthma/COPD",
        "Non-selective beta-blockers block β2 receptors needed for bronchodilation",
        "Avoid non-selective beta-blockers in asthma. Use cardioselective (bisoprolol) if essential.",
    ),
    (
        ["montelukast"],
        ["phenobarbital", "rifampin", "phenytoin"],
        "moderate",
        "CYP3A4/2C8 inducers reduce montelukast effectiveness",
        "Increased montelukast metabolism via enzyme induction",
        "Monitor asthma control. May need alternative leukotriene modifier or dose adjustment.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 9. MUSCULOSKELETAL / PAIN
    # ═══════════════════════════════════════════════════════════════
    (
        ["nsaid", "ibuprofen", "naproxen", "diclofenac"],
        ["aspirin"],
        "moderate",
        "NSAIDs may reduce aspirin's cardioprotective antiplatelet effect",
        "Ibuprofen competes for COX-1 binding site, blocking aspirin's irreversible acetylation",
        "Take aspirin 30 min before or 8h after ibuprofen. Naproxen has less interference.",
    ),
    (
        ["nsaid", "ibuprofen", "naproxen", "diclofenac", "ketorolac"],
        ["ace inhibitor", "enalapril", "lisinopril", "arb", "losartan", "valsartan"],
        "moderate",
        "NSAIDs reduce antihypertensive effect and increase renal impairment risk",
        "NSAIDs inhibit renal prostaglandins needed for RAAS-dependent renal perfusion",
        "Avoid long-term combination. Monitor BP and renal function. Use acetaminophen when possible.",
    ),
    (
        ["nsaid", "ibuprofen", "naproxen", "diclofenac"],
        ["ssri", "fluoxetine", "sertraline", "paroxetine"],
        "moderate",
        "NSAIDs + SSRIs increase GI bleeding risk 6-fold vs either alone",
        "SSRIs deplete platelet serotonin; NSAIDs damage gastric mucosa — synergistic bleeding",
        "Co-prescribe PPI for gastric protection. Use acetaminophen when possible.",
    ),
    (
        ["nsaid", "ibuprofen", "naproxen", "diclofenac"],
        ["furosemide", "loop diuretic", "thiazide", "hydrochlorothiazide"],
        "moderate",
        "NSAIDs reduce diuretic and antihypertensive efficacy — fluid retention",
        "NSAIDs inhibit renal prostaglandins needed for sodium/water excretion",
        "Monitor blood pressure, weight, and edema. Avoid long-term combination.",
    ),
    (
        ["colchicine"],
        ["clarithromycin", "erythromycin", "ketoconazole", "ritonavir"],
        "contraindicated",
        "CYP3A4/P-gp inhibitors with colchicine — fatal toxicity reported",
        "Colchicine metabolism significantly impaired; narrow therapeutic index",
        "Contraindicated in renal/hepatic impairment. If used, reduce colchicine to single dose. Monitor CBC.",
    ),
    (
        ["colchicine"],
        ["cyclosporine"],
        "high",
        "Both drugs are P-gp substrates — increased colchicine toxicity",
        "Cyclosporine inhibits P-gp and may impair colchicine clearance",
        "Reduce colchicine dose. Monitor for myopathy and diarrhea. Check CBC regularly.",
    ),
    (
        ["opioid", "morphine", "oxycodone", "fentanyl", "codeine", "tramadol"],
        ["gabapentin", "pregabalin"],
        "high",
        "Additive CNS depression — respiratory depression risk especially with gabapentinoids",
        "Both cause CNS/respiratory depression; gabapentinoids potentiate opioid effects",
        "FDA warning. Start with lower doses. Monitor respiratory status. Avoid in elderly/comorbid patients.",
    ),
    (
        ["opioid", "morphine", "oxycodone", "fentanyl"],
        ["muscle relaxant", "cyclobenzaprine", "tizanidine", "baclofen", "methocarbamol"],
        "high",
        "Additive CNS and respiratory depression",
        "Both classes depress the central nervous system",
        "Use lowest effective doses. Monitor for excessive sedation. Avoid in elderly patients.",
    ),
    (
        ["tramadol"],
        ["carbamazepine"],
        "moderate",
        "Carbamazepine reduces tramadol effectiveness",
        "CYP3A4 induction increases tramadol metabolism; reduced analgesic effect",
        "Higher tramadol doses may be needed. Monitor pain control. Consider alternative analgesic.",
    ),
    (
        ["tramadol"],
        ["ondansetron"],
        "moderate",
        "Ondansetron may reduce tramadol's analgesic effect",
        "5-HT3 antagonism by ondansetron blocks serotonergic component of tramadol's analgesia",
        "Monitor pain control. Consider alternative antiemetic or analgesic.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 10. ENDOCRINE / THYROID / MISCELLANEOUS
    # ═══════════════════════════════════════════════════════════════
    (
        ["potassium", "potassium chloride", "kcl"],
        ["spironolactone", "eplerenone", "amiloride", "triamterene"],
        "high",
        "Combined potassium supplementation with potassium-sparing diuretics — severe hyperkalemia",
        "Additive potassium retention",
        "Avoid combination unless documented hypokalemia. Monitor K+ every 2–3 days initially.",
    ),
    (
        ["corticosteroid", "prednisone", "prednisolone", "dexamethasone", "methylprednisolone"],
        ["nsaid", "ibuprofen", "naproxen", "aspirin"],
        "moderate",
        "Increased risk of GI ulceration and bleeding",
        "Both independently damage gastric mucosa; combination is synergistic",
        "Co-prescribe PPI for gastric protection. Limit duration. Monitor for GI symptoms.",
    ),
    (
        ["corticosteroid", "prednisone", "prednisolone", "dexamethasone"],
        ["warfarin", "coumadin"],
        "moderate",
        "Corticosteroids may increase or decrease warfarin effect unpredictably",
        "Altered clotting factor synthesis and CYP enzyme effects vary by steroid type and dose",
        "Monitor INR within 3–5 days of starting or changing corticosteroid dose.",
    ),
    (
        ["phenytoin", "dilantin"],
        ["fluconazole", "isoniazid", "omeprazole", "amiodarone"],
        "high",
        "Increased phenytoin levels — toxicity (nystagmus, ataxia, seizures)",
        "CYP2C9/CYP2C19 inhibition slows phenytoin metabolism",
        "Monitor phenytoin levels. Reduce dose. Watch for toxicity signs: ataxia, nystagmus, drowsiness.",
    ),
    (
        ["phenytoin", "dilantin", "carbamazepine", "tegretol"],
        ["oral contraceptive", "ethinyl estradiol"],
        "high",
        "Enzyme-inducing AEDs reduce contraceptive effectiveness",
        "CYP3A4 induction accelerates estrogen/progestin metabolism",
        "Use non-hormonal or high-dose hormonal contraception. IUD is preferred.",
    ),
    (
        ["levothyroxine", "synthroid"],
        ["calcium", "calcium carbonate"],
        "moderate",
        "Calcium reduces levothyroxine absorption by 25–30%",
        "Calcium forms insoluble complexes with levothyroxine in the GI tract",
        "Separate administration by at least 4 hours. Take levothyroxine on empty stomach 30 min before food.",
    ),
    (
        ["levothyroxine", "synthroid"],
        ["iron", "ferrous sulfate"],
        "moderate",
        "Iron reduces levothyroxine absorption significantly",
        "Iron forms insoluble complexes with levothyroxine",
        "Separate by at least 4 hours. Monitor TSH levels.",
    ),
    (
        ["levothyroxine", "synthroid"],
        ["cholestyramine", "colestipol", "colesevelam"],
        "high",
        "Bile acid sequestrants bind levothyroxine — dramatically reduced absorption",
        "Sequestrants bind T4 in the GI tract preventing absorption",
        "Separate by at least 4–6 hours. Take levothyroxine first in the morning.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 11. ANESTHESIA / PERIOPERATIVE
    # ═══════════════════════════════════════════════════════════════
    (
        ["succinylcholine"],
        ["cholinesterase inhibitor", "neostigmine", "pyridostigmine", "donepezil"],
        "high",
        "Cholinesterase inhibitors prolong succinylcholine's neuromuscular blockade",
        "Reduced breakdown of succinylcholine by inhibited plasma cholinesterase",
        "Monitor neuromuscular function closely. May need extended ventilatory support.",
    ),
    (
        ["ketamine"],
        ["theophylline", "aminophylline"],
        "high",
        "Increased seizure risk with ketamine + theophylline combination",
        "Both lower the seizure threshold via different mechanisms",
        "Avoid combination. If both needed, ensure seizure monitoring and have benzodiazepine available.",
    ),
    (
        ["propofol"],
        ["fentanyl", "alfentanil", "remifentanil"],
        "moderate",
        "Synergistic respiratory and cardiovascular depression",
        "Additive CNS depression; both reduce respiratory drive and blood pressure",
        "Reduce doses of both agents. Titrate carefully. Standard in anesthesia with proper monitoring.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 12. ANTIRETROVIRALS (HIV)
    # ═══════════════════════════════════════════════════════════════
    (
        ["ritonavir", "cobicistat"],
        ["simvastatin", "lovastatin"],
        "contraindicated",
        "Boosted PI dramatically increases statin levels — fatal rhabdomyolysis reported",
        "Potent CYP3A4 inhibition prevents statin metabolism",
        "Contraindicated. Use pravastatin, rosuvastatin (low dose), or pitavastatin.",
    ),
    (
        ["ritonavir", "cobicistat"],
        ["midazolam", "triazolam"],
        "contraindicated",
        "Protease inhibitors cause extreme benzodiazepine accumulation — prolonged sedation",
        "CYP3A4 inhibition prevents benzodiazepine metabolism",
        "Contraindicated. Use lorazepam, oxazepam (glucuronidation, not CYP3A4) as alternatives.",
    ),
    (
        ["ritonavir", "cobicistat"],
        ["fluticasone", "budesonide"],
        "high",
        "Boosted PIs dramatically increase inhaled corticosteroid levels — Cushing syndrome",
        "CYP3A4 inhibition prevents corticosteroid metabolism even from inhaled route",
        "Use beclomethasone (not CYP3A4 metabolized) instead. Monitor for Cushingoid features.",
    ),
    (
        ["efavirenz", "nevirapine"],
        ["oral contraceptive", "ethinyl estradiol"],
        "high",
        "NNRTIs reduce contraceptive effectiveness via CYP3A4 induction",
        "CYP3A4 induction accelerates estrogen metabolism",
        "Use additional contraception (condom) or non-hormonal method. Consider depot medroxyprogesterone.",
    ),
    (
        ["tenofovir"],
        ["nsaid", "ibuprofen", "naproxen", "diclofenac"],
        "moderate",
        "NSAIDs increase tenofovir nephrotoxicity risk",
        "NSAIDs reduce renal blood flow; tenofovir causes proximal tubular damage",
        "Monitor renal function. Avoid long-term NSAID use. Use acetaminophen for pain.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 13. PEDIATRIC-SPECIFIC INTERACTIONS
    # ═══════════════════════════════════════════════════════════════
    (
        ["aspirin", "acetylsalicylic acid"],
        ["varicella vaccine", "influenza", "viral illness"],
        "contraindicated",
        "Reye syndrome risk in children with viral illness + aspirin",
        "Aspirin use during viral infections triggers hepatic/CNS mitochondrial injury in children",
        "Absolutely contraindicated in children <18 years during viral illness. Use acetaminophen/ibuprofen instead.",
    ),
    (
        ["metoclopramide"],
        ["levodopa"],
        "moderate",
        "Metoclopramide blocks dopamine receptors — worsens Parkinsonian symptoms",
        "D2 receptor antagonism by metoclopramide opposes levodopa's mechanism of action",
        "Avoid in Parkinson's patients. Use domperidone (doesn't cross BBB) for GI motility.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 14. HERBAL & SUPPLEMENT INTERACTIONS
    # ═══════════════════════════════════════════════════════════════
    (
        ["st john's wort", "hypericum"],
        ["ssri", "fluoxetine", "sertraline", "paroxetine", "citalopram"],
        "high",
        "Serotonin syndrome risk — St. John's Wort is a serotonin reuptake inhibitor",
        "Additive serotonergic activity",
        "Avoid combination. If patient using St. John's Wort, do not start SSRI until 2 weeks after stopping.",
    ),
    (
        ["st john's wort", "hypericum"],
        ["oral contraceptive", "ethinyl estradiol"],
        "high",
        "St. John's Wort reduces contraceptive effectiveness — breakthrough bleeding/pregnancy",
        "CYP3A4 and P-glycoprotein induction by hyperforin",
        "Avoid combination. Use additional contraception if patient refuses to stop supplement.",
    ),
    (
        ["st john's wort", "hypericum"],
        ["cyclosporine", "tacrolimus"],
        "contraindicated",
        "St. John's Wort reduces immunosuppressant levels — organ rejection risk",
        "Potent CYP3A4 and P-glycoprotein induction",
        "Absolutely contraindicated in transplant patients. Can cause acute rejection episodes.",
    ),
    (
        ["st john's wort", "hypericum"],
        ["warfarin", "coumadin"],
        "high",
        "St. John's Wort reduces warfarin effectiveness",
        "CYP induction accelerates warfarin metabolism",
        "Avoid combination. Monitor INR if patient starts or stops St. John's Wort.",
    ),
    (
        ["ginkgo biloba"],
        ["warfarin", "aspirin", "clopidogrel", "anticoagulant"],
        "moderate",
        "Ginkgo may increase bleeding risk with anticoagulants/antiplatelets",
        "Ginkgo inhibits platelet-activating factor and has antiplatelet properties",
        "Advise patients to inform doctor of ginkgo use. Monitor for bleeding signs.",
    ),
    (
        ["ginseng"],
        ["warfarin", "coumadin"],
        "moderate",
        "Ginseng may reduce warfarin effectiveness",
        "Possible CYP induction and antiplatelet effects — variable and unpredictable",
        "Monitor INR. Advise consistent use or avoidance. Effects may vary by ginseng species.",
    ),
    (
        ["kava"],
        ["benzodiazepine", "alcohol", "sedative"],
        "high",
        "Kava potentiates sedative effects — excessive CNS depression",
        "Kavalactones enhance GABA-A receptor activity similar to benzodiazepines",
        "Avoid combination. Risk of hepatotoxicity from kava alone. Counsel patients.",
    ),
    (
        ["garlic supplement"],
        ["warfarin", "anticoagulant", "antiplatelet"],
        "low",
        "Garlic supplements may mildly increase bleeding risk",
        "Garlic has antiplatelet properties (inhibits thromboxane synthesis)",
        "Inform patients of potential risk. Recommend stopping 7 days before surgery.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 15. NEPHROLOGY-SPECIFIC
    # ═══════════════════════════════════════════════════════════════
    (
        ["nsaid", "ibuprofen", "naproxen", "diclofenac"],
        ["ace inhibitor", "enalapril", "lisinopril"],
        "high",
        "'Triple whammy' with diuretic — acute kidney injury risk when all three combined",
        "NSAIDs + ACE-I + diuretic causes afferent/efferent arteriole dysfunction and volume depletion",
        "The ACE-I + NSAID + diuretic triple combination is particularly dangerous. Avoid if possible.",
    ),
    (
        ["lithium"],
        ["nsaid", "ace inhibitor", "diuretic"],
        "high",
        "Triple combination dramatically increases lithium toxicity risk",
        "NSAIDs reduce renal clearance; ACE-I reduces GFR; diuretics deplete sodium",
        "If >1 of these combined with lithium, monitor lithium levels very frequently.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 16. TRANSPLANT-SPECIFIC
    # ═══════════════════════════════════════════════════════════════
    (
        ["sirolimus", "everolimus"],
        ["cyclosporine"],
        "high",
        "Cyclosporine increases sirolimus/everolimus levels significantly",
        "CYP3A4 and P-gp inhibition by cyclosporine; additive nephrotoxicity",
        "Separate administration by 4 hours. Monitor trough levels of both. Adjust doses accordingly.",
    ),
    (
        ["sirolimus", "everolimus"],
        ["voriconazole", "posaconazole"],
        "contraindicated",
        "Azoles dramatically increase mTOR inhibitor levels — fatal toxicity possible",
        "CYP3A4 inhibition causes profound accumulation",
        "Contraindicated. If antifungal essential, use echinocandin (caspofungin, micafungin) instead.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 17. OBSTETRIC/GYNECOLOGY
    # ═══════════════════════════════════════════════════════════════
    (
        ["misoprostol"],
        ["nsaid", "ibuprofen", "naproxen"],
        "low",
        "NSAIDs may reduce misoprostol's gastroprotective effect but combination is sometimes intentional",
        "NSAIDs inhibit prostaglandin synthesis while misoprostol is a prostaglandin analog",
        "When used for GI protection with NSAIDs, this is intentional and therapeutic.",
    ),
    (
        ["magnesium sulfate"],
        ["nifedipine"],
        "high",
        "Severe hypotension and neuromuscular blockade risk in preeclampsia treatment",
        "Both cause vasodilation and muscle relaxation; magnesium potentiates calcium channel blockade",
        "Monitor blood pressure closely. Watch for signs of magnesium toxicity (loss of reflexes, respiratory depression).",
    ),
    (
        ["oxytocin"],
        ["prostaglandin", "misoprostol", "dinoprostone"],
        "high",
        "Uterine hyperstimulation — risk of uterine rupture",
        "Additive uterotonic effect from dual stimulation",
        "Allow adequate interval between agents. Monitor fetal heart rate and uterine activity closely.",
    ),

    # ═══════════════════════════════════════════════════════════════
    # 18. OPHTHALMOLOGY
    # ═══════════════════════════════════════════════════════════════
    (
        ["timolol eye drops", "betaxolol eye drops"],
        ["verapamil", "diltiazem"],
        "moderate",
        "Systemic absorption of ophthalmic beta-blockers can cause bradycardia with CCBs",
        "Topical beta-blockers are absorbed systemically; additive cardiac depression",
        "Monitor heart rate. Consider switching to non-beta-blocker glaucoma drops (latanoprost, brimonidine).",
    ),
    (
        ["timolol eye drops"],
        ["salbutamol", "albuterol", "beta-agonist"],
        "moderate",
        "Ophthalmic timolol may cause systemic beta-blockade — worsens asthma/COPD",
        "Systemic absorption of timolol blocks β2 receptors despite topical application",
        "Avoid timolol in asthma/COPD patients. Use betaxolol (β1-selective) or non-beta-blocker alternatives.",
    ),
]

# ── Total count (for reference) ──
INTERACTION_COUNT = len(INTERACTION_DB)  # ~200+ clinically validated interaction entries
